
---
 - hosts: headnode
   tasks: 

   - name: set files to provision
     command: wwsh -y provision set "comp*" --files=passwd,group,shadow,munge.key,slurm.conf,dynamic_hosts,network

   - name: tell nodes to get files
     command: pdsh -w comp[0-{{ num_nodes|int - 1 }}] /warewulf/bin/wwgetfiles

   - name: start munge
     service: name=munge state=restarted

   - name: start slurmctld
     service: name=slurmctld state=restarted

   - name: start munge on compute nodes
     shell: pdsh -w comp{0..{{ num_nodes|int - 1 }}} systemctl start munge

   - name: start slurmd on compute nodes
     shell: pdsh -w comp{0..{{ num_nodes|int - 1 }}} systemctl start slurmd

   - name: update slurm status on nodes
     command: scontrol update nodename=comp[0-{{ num_nodes|int - 1 }}] state=idle

   vars_prompt:
    - name: "num_nodes"
      prompt: "How many compute nodes do you have?"
      private: no
      default: 0
